# -*- coding: utf-8 -*-
"""1RVU23CSE485_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZLpB0rpkCkrgvdzJkQ8hKlkeGmOF0fA
"""

!pip install --upgrade pip
!pip install transformers datasets sentence-transformers fastai[transformers] torch torchvision torchaudio --quiet
# Optional helpers
!pip install kaggle --quiet
# Verify installs (short)

import sys, pkgutil
for pkg in ("transformers","datasets","sentence_transformers","fastai","kaggle","torch"):
  print(pkg, "installed:", pkgutil.find_loader(pkg) is not None)

import kagglehub
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

from transformers import pipeline
# Create a sentiment-analysis pipeline (uses a small fine-tuned model)
sentiment = pipeline("sentiment-analysis")
# default: distilbert-base-uncased-finetuned-sst-2-english
texts = [
"I loved the new movie! The acting was great and the plot was exciting.",
"This product was terrible. It broke on day 2 and customer support was unhelpful."
]
results = sentiment(texts)
for t, r in zip(texts, results):
  print(t)
  print(" ->", r)
  print()

translator = pipeline("translation_en_to_de") # default model: Helsinki/opus-mt-en-de
text = "Machine learning is changing the world. It's exciting!"
print(translator(text, max_length=100))

"""## Trying English to French on 20 sentences"""

translator = pipeline("translation_en_to_fr") # default model: Helsinki/opus-mt-en-de
text= ["Machine learning is changing the world. It's exciting!", "The weather is pleasant today.","She completed her assignment before the deadline.",
      "Technology is changing the way people communicate.","He forgot to bring his notebook to class.","The movie received positive reviews from critics.",
       "Students are preparing for their final examinations.", "The train arrived at the station on time.","She enjoys reading books in her free time.",
       "The meeting was postponed due to technical issues.","Social media influences public opinion significantly.","He is learning programming to improve his skills.",
       "The new restaurant offers delicious vegetarian food.","The company announced a new product launch.","The internet provides access to vast amounts of information.",
       "He regularly exercises to stay healthy.","Online education has become more popular after the pandemic.","She solved the problem using a simple approach.",
       "The presentation explained the concept very clearly.","Many people prefer working from home now."]
for i in range(0,20):
  print(translator(text[i], max_length=100))

summarizer = pipeline("summarization") # usually uses facebook/bart-large-cnn or t5
article = """
The field of artificial intelligence has seen dramatic progress in recent years.
Large language models now perform many tasks previously believed to require human
intelligence.
Researchers continue to push the bounds by scaling models and improving pretraining and
fine-tuning techniques.
"""
print("Summary:\n", summarizer(article, max_length=60, min_length=20,
do_sample=False)[0]['summary_text'])

ner = pipeline("ner", grouped_entities=True)
text = "Barack Obama was born in Hawaii and served as the President of the United States."
print(ner(text))

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2') # compact, fast, good quality
sentences = [
"How do I cook pasta?",
"Best ways to boil spaghetti",
"What is the capital of France?"
]
embeddings = model.encode(sentences, convert_to_tensor=True)
print("Embeddings shape:", embeddings.shape)

query = "How to make spaghetti?"
q_emb = model.encode(query, convert_to_tensor=True)
scores = util.pytorch_cos_sim(q_emb, embeddings)[0]
for s, score in zip(sentences, scores):
  print(f"{score.item():.3f}\t{s}")

# FastAI text classification (simple)
from datasets import load_dataset
from fastai.text.all import (
    TextDataLoaders,
    text_classifier_learner,
    AWD_LSTM,
    accuracy
)
# Load dataset (uses 'imdb' dataset from HF datasets)
ds = load_dataset("imdb")
print(ds)
# Use a small subset for the lab to run quickly (optional)
small_train = ds['train'].shuffle(seed=42).select(range(4000)) # 4k samples

small_test = ds['test'].shuffle(seed=42).select(range(2000)) # 2k samples
# Convert to DataFrame for fastai
import pandas as pd
train_df = pd.DataFrame(small_train)
test_df = pd.DataFrame(small_test)
# fastai DataBlock
dls = TextDataLoaders.from_df(train_df, text_col='text', label_col='label', valid_pct=0.1, bs=32)
learn = text_classifier_learner(dls,AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.fine_tune(1)

from datasets import load_dataset
from transformers import AutoTokenizer
dataset = load_dataset("glue", "sst2")
print(dataset['train'][0])
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_fn(batch):
  return tokenizer(batch['sentence'], truncation=True, padding='max_length', max_length=128)
tokenized = dataset.map(tokenize_fn, batched=True)
print(tokenized['train'][0])

import csv
texts = [
"I love this phone. The battery life is excellent.",
"Worst purchase ever. It stopped working after two days."
]
results = sentiment(texts)
with open("sentiment_results.csv", "w", newline="") as f:
  writer = csv.writer(f)
  writer.writerow(["text", "label", "score"])
  for t, r in zip(texts, results):
    writer.writerow([t, r['label'], r['score']])
print("Saved sentiment_results.csv")

