# -*- coding: utf-8 -*-
"""1RVU23CSE485_Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIlS4-XT0XGGr_4h21aHbizu_3pdabZQ
"""

# LAB 3: Prompt Engineering Patterns & Conversation Memory
# Google Colab + LangChain + Hugging Face
# STEP 1: Install required libraries
!pip install -q langchain langchain-community transformers accelerate sentencepiece

import requests
print(requests.__version__)

# STEP 2: Load Hugging Face LLM (FLAN-T5)
from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

hf_pipeline = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_length=256
)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

# STEP 3: Import PromptTemplate
from langchain_core.prompts import PromptTemplate

# STEP 4: Demonstration WITHOUT Memory (Problem)
simple_prompt = PromptTemplate(
    input_variables=["question"],
    template="Answer the question:\n{question}"
)

print(llm.invoke(simple_prompt.format(
    question="Who is Donald Trump?"
)))

print(llm.invoke(simple_prompt.format(
    question="What is his wife name?"
)))

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

prompt = ChatPromptTemplate.from_messages([
    # This placeholder is where the previous "Human: / AI:" turns go
    MessagesPlaceholder(variable_name="history"),
    ("human", "{question}"),
])

# 2. Create the chain using YOUR existing 'llm' object
chain = prompt | llm

# 3. Define the session history storage
store = {}

def get_session_history(session_id: str):
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

# 4. Wrap the chain to add memory
chain_with_history = RunnableWithMessageHistory(
    chain,
    get_session_history,
    input_messages_key="question",
    history_messages_key="history",
)

# Question 1
response1 = chain_with_history.invoke(
    {"question": "Who is Donald Trump?"},
    config={"configurable": {"session_id": "session_1"}}
)
print(f"Q1: {response1}")

# Question 2 (Relies on context)
response2 = chain_with_history.invoke(
    {"question": "What is his wife's name?"},
    config={"configurable": {"session_id": "session_1"}}
)
print(f"Q2: {response2}")